### PR TITLE
fix overflow bug and add regression test

### LINKED ISSUE #16: xorKeyStreamAVX2 mishandles counter overflow
Repro:
```go
func TestOverflow(t *testing.T) {
	nonce := make([]byte, 8)
	key := make([]byte, 32)
	stream, _ := NewCipher(nonce, key, 20)

	// Set the counter to uint64-max and encrypt a two-block plaintext. This
	// should cause the counter to overflow to 1.
	plaintext := []byte("This is an example plaintext " +
		" that should require two blocks to encrypt")
	ciphertext := make([]byte, len(plaintext))
	stream.SetCounter(^uint64(0))
	stream.XORKeyStream(ciphertext, plaintext)

	// Reset the counter to 0 and attempt the decrypt the second block of the
	// ciphertext.
	stream.SetCounter(0)
	plaintextSuffix := make([]byte, len(plaintext[64:]))
	stream.XORKeyStream(plaintextSuffix, ciphertext[64:])
	if !bytes.Equal(plaintextSuffix, plaintext[64:]) {
		t.Fatal("failed to decrypt second block")
	}
}
```

When `xorKeyStream` is `xorKeyStreamAVX2`, this test fails. For any other value of `xorKeyStream`, it succeeds.

One other useful piece of info: If I split the initial xor into two calls, i.e.:
```go
stream.SetCounter(^uint64(0))
stream.XORKeyStream(ciphertext[:64], plaintext[:64])
stream.XORKeyStream(ciphertext[64:], plaintext[64:])
```
the decryption succeeds.

### PR DESCRIPTION
**Pull request by lukechampine**
As far as I can tell, this fixes #16. The bug, as @jedisct1 pointed out, was related to incrementing Y3 incorrectly; he believed that the counter was overflowing into the nonce. Switching from `VPADDD` to `VPADDQ` causes the overflow behavior to match the reference implementation: the counter resets to 0 and the nonce is unchanged.

I've tested this with all nonce sizes and it seems okay. Let me know if there are any other edge cases I should test.

### CODE REVIEW

**Comment by jedisct1** [comment]
The internal counter must not repeat. If it does, security guarantees of the primitive collapse. People should have learned from WEP.

When an overflow happens, it's perfectly acceptable to increment the nonce. If you happen to encrypt huge messages, you probably don't increment nonces anyway, so the current behavior is safer than just wrapping the counter.

That being said, it's very unlikely that you own a computer with so much memory and processing power.

The only scenario where you might be overflowing a 2^64 bit internal counter is when you didn't get the meaning of *internal counter*.

Your applications should not mess with it or set it to something funny. The highest initial value in existing constructions is 1.

I'm not sure that `SetCounter()` should be exposed at all.

**Comment by jedisct1** [comment]
> I need SetCounter because I want to provide random access within the encrypted stream

Which still doesn't mean that counters should ever overflow. And also means that you probably don't authenticate the data. It just confirms that giving access to internal counters is a terrible idea.

**Comment by lukechampine** [comment]
correct, counters should not overflow in my use case. This PR isn't intended to address any problems in my code, it just fixes an incongruity that I noticed. Also, wrt exposing the counter, most users will import the higher-level `chacha20` package anyway, which doesn't provide access to the counter.

I don't do "true" authentication, but I do verify integrity. If you know the Merkle root of a file, then you can verify the integrity of any subset of 64-byte blocks via Merkle proof. So you get random access at 64-byte granularity without needing to store a separate checksum for each block.

**Comment by aead** [comment]
My thoughts about this issue:
1. The general description of a stream cipher requires that the nonce/iv is never repeated - which means in particular that it should not overflow.
2. AFAIK it is not specified (for (X)ChaCha) how a counter overflow should be handled -> undefined behavior.

My conclusion:
The stream cipher should detect an overflow and panic. Especially ChaCha20 (with a 96 bit nonce) can be affected by this issue since it is feasible for real-world applications to exceed the 256 GB limit. Then incrementing the nonce by 1 results in repeating the internal nonce.
```
        nonce := make([]byte, INonceSize)
	key := make([]byte, KeySize)
	var counter uint32 = 0

	binary.LittleEndian.PutUint32(nonce, counter)
	stream, _ := NewCipher(nonce, key, 20)

	// Set the counter to uint64-max and encrypt a two-block plaintext. This
	// should cause the counter to overflow to 1.
	plaintext := []byte("This is an example plaintext " +
		" that should require two blocks to encrypt")
	ciphertext := make([]byte, len(plaintext))
	stream.SetCounter(^uint64(0))
	stream.XORKeyStream(ciphertext, plaintext)

	counter++
	binary.LittleEndian.PutUint32(nonce, counter)
	stream, _ = NewCipher(nonce, key, 20)

	plaintextSuffix := make([]byte, len(plaintext[64:]))
	stream.XORKeyStream(plaintextSuffix, ciphertext[64:])
	if !bytes.Equal(plaintextSuffix, plaintext[64:]) {
		t.Fatal("failed to decrypt second block")
	}
```

Further I agree with @jedisct1 that `SetCounter` is a dangerous API call. I don't see how it can be implement to be consistent (and to avoid nonce repetition). 

> This is one of the big advantages of chacha (and CTR mode in general) IMO, and it saddens me that many APIs (such as Go's cipher.Stream) do not provide access to the counter.

Actually Go's crypto implementations try to avoid misuse pitfalls. For example `cipher.AEAD` does not provide a streaming API for a similar reason. Further IMO non-AEAD schemes should be considered "legacy-crypto". However this does not mean that random-access cannot be realized...

**Comment by lukechampine** [comment]
panic on overflow is fine by me. I just want AVX2 to be consistent with the others so that it can be re-enabled. :)

**Comment by aead** [comment]
Closing this because of #30

**Pull request closed without merging**
